version: "3.9"
services:
  humble-tb3_mrc-docker:
    extends:
      file: humble-tb3_mrc-compose.yml
      service: humble-tb3_mrc-docker
    environment:
      # GPU access
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
