export ROS_DOMAIN_ID=6
export ROS_LOCALHOST_ONLY=0

export TURTLEBOT3_MODEL=waffle_pi

# export RMW_IMPLEMENTATION=rmw_fastrtps_cpp

# export ROS_SUPER_CLIENT=TRUE
# export ROS_DISCOVERY_SERVER="192.168.79.228:11811"

# export FASTRTPS_DEFAULT_PROFILES_FILE=$HOME/${WS_DIR}/config/fastdds_mrc.xml
